version: '3.8'

services:
  yolo-api:
    build:
      context: ./model
      dockerfile: Dockerfile
    container_name: yolo-detection-api
    network_mode: "host"
    ports:
      - "8080:8080"
    volumes:
      - ./model:/app/model
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
  yolo-bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: yolo-bot
    ports:
      - "3001:3001"
    restart: unless-stopped